//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.225
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Toolbox.GUI.DX.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Toolbox.GUI.DX.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Abort.
        /// </summary>
        public static string ABORT {
            get {
                return ResourceManager.GetString("ABORT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        public static string ABOUT_TITLE {
            get {
                return ResourceManager.GetString("ABOUT_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Allow only one instance.
        /// </summary>
        public static string ALLOW_ONE_INSTANCE {
            get {
                return ResourceManager.GetString("ALLOW_ONE_INSTANCE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This application is not ClickOnce.
        /// </summary>
        public static string APLLICATION_IS_NOT_CLICKONCE {
            get {
                return ResourceManager.GetString("APLLICATION_IS_NOT_CLICKONCE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Application Settings.
        /// </summary>
        public static string APPLICATION_SETTINGS {
            get {
                return ResourceManager.GetString("APPLICATION_SETTINGS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string CANCEL {
            get {
                return ResourceManager.GetString("CANCEL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancelling….
        /// </summary>
        public static string CANCELLING {
            get {
                return ResourceManager.GetString("CANCELLING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear.
        /// </summary>
        public static string CLEAR {
            get {
                return ResourceManager.GetString("CLEAR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        public static string CLOSE {
            get {
                return ResourceManager.GetString("CLOSE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close on critical error.
        /// </summary>
        public static string CLOSE_ON_CRITICAL_ERROR {
            get {
                return ResourceManager.GetString("CLOSE_ON_CRITICAL_ERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Event time.
        /// </summary>
        public static string COL_EVENT_TIME {
            get {
                return ResourceManager.GetString("COL_EVENT_TIME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Message.
        /// </summary>
        public static string COL_MESSAGE {
            get {
                return ResourceManager.GetString("COL_MESSAGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Source.
        /// </summary>
        public static string COL_SOURCE {
            get {
                return ResourceManager.GetString("COL_SOURCE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current version.
        /// </summary>
        public static string CURRENT_VERSION {
            get {
                return ResourceManager.GetString("CURRENT_VERSION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Debug.
        /// </summary>
        public static string DEBUG_COUNT {
            get {
                return ResourceManager.GetString("DEBUG_COUNT", resourceCulture);
            }
        }
        
        public static System.Drawing.Bitmap DefaultSplash {
            get {
                object obj = ResourceManager.GetObject("DefaultSplash", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure to delete item?.
        /// </summary>
        public static string DELETE_CONFIRM {
            get {
                return ResourceManager.GetString("DELETE_CONFIRM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Developed by.
        /// </summary>
        public static string DEVELOPED_TITLE {
            get {
                return ResourceManager.GetString("DEVELOPED_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Don&apos;t close on critical error.
        /// </summary>
        public static string DONT_CLOSE {
            get {
                return ResourceManager.GetString("DONT_CLOSE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Errors.
        /// </summary>
        public static string ERRORS_COUNT {
            get {
                return ResourceManager.GetString("ERRORS_COUNT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Call stack.
        /// </summary>
        public static string EXCEPTION_CALLSTACK {
            get {
                return ResourceManager.GetString("EXCEPTION_CALLSTACK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Message.
        /// </summary>
        public static string EXCEPTION_MESSAGE {
            get {
                return ResourceManager.GetString("EXCEPTION_MESSAGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Source.
        /// </summary>
        public static string EXCEPTION_SOURCE {
            get {
                return ResourceManager.GetString("EXCEPTION_SOURCE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type.
        /// </summary>
        public static string EXCEPTION_TYPE {
            get {
                return ResourceManager.GetString("EXCEPTION_TYPE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failure.
        /// </summary>
        public static string FAIL {
            get {
                return ResourceManager.GetString("FAIL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Font settings.
        /// </summary>
        public static string FONT_SETTINGS {
            get {
                return ResourceManager.GetString("FONT_SETTINGS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Icon.
        /// </summary>
        public static string ICON {
            get {
                return ResourceManager.GetString("ICON", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ignore.
        /// </summary>
        public static string IGNORE {
            get {
                return ResourceManager.GetString("IGNORE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Additional Info.
        /// </summary>
        public static string INFO_TITLE {
            get {
                return ResourceManager.GetString("INFO_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Message window.
        /// </summary>
        public static string INFO_WND {
            get {
                return ResourceManager.GetString("INFO_WND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kill.
        /// </summary>
        public static string KILL_TASK {
            get {
                return ResourceManager.GetString("KILL_TASK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure to kill the task {0}?.
        /// </summary>
        public static string KILL_TASK_CONFIRM {
            get {
                return ResourceManager.GetString("KILL_TASK_CONFIRM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Level.
        /// </summary>
        public static string LEVEL {
            get {
                return ResourceManager.GetString("LEVEL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to List to end.
        /// </summary>
        public static string LIST_TO_END {
            get {
                return ResourceManager.GetString("LIST_TO_END", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Locale.
        /// </summary>
        public static string LOCALE {
            get {
                return ResourceManager.GetString("LOCALE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to English.
        /// </summary>
        public static string LOCALE_ENGLISH {
            get {
                return ResourceManager.GetString("LOCALE_ENGLISH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Russian.
        /// </summary>
        public static string LOCALE_RUSSIAN {
            get {
                return ResourceManager.GetString("LOCALE_RUSSIAN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log.
        /// </summary>
        public static string LOG {
            get {
                return ResourceManager.GetString("LOG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All.
        /// </summary>
        public static string LOG_LEVEL_ALL {
            get {
                return ResourceManager.GetString("LOG_LEVEL_ALL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        public static string LOG_LEVEL_ERROR {
            get {
                return ResourceManager.GetString("LOG_LEVEL_ERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Info.
        /// </summary>
        public static string LOG_LEVEL_INFO {
            get {
                return ResourceManager.GetString("LOG_LEVEL_INFO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warning.
        /// </summary>
        public static string LOG_LEVEL_WARN {
            get {
                return ResourceManager.GetString("LOG_LEVEL_WARN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Minimal level.
        /// </summary>
        public static string LOG_MIN_LEVEL {
            get {
                return ResourceManager.GetString("LOG_MIN_LEVEL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show Log File.
        /// </summary>
        public static string LOG_SHOW_FILE_TITLE {
            get {
                return ResourceManager.GetString("LOG_SHOW_FILE_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Messages.
        /// </summary>
        public static string MESSAGES_COUNT {
            get {
                return ResourceManager.GetString("MESSAGES_COUNT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modules.
        /// </summary>
        public static string MODULES_TITLE {
            get {
                return ResourceManager.GetString("MODULES_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Multi edit.
        /// </summary>
        public static string MultiEdit {
            get {
                return ResourceManager.GetString("MultiEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string NAME {
            get {
                return ResourceManager.GetString("NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No.
        /// </summary>
        public static string NO {
            get {
                return ResourceManager.GetString("NO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        public static string OK {
            get {
                return ResourceManager.GetString("OK", resourceCulture);
            }
        }
        
        public static System.Drawing.Bitmap p_32_app_config {
            get {
                object obj = ResourceManager.GetObject("p_32_app_config", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap p_32_document_config {
            get {
                object obj = ResourceManager.GetObject("p_32_document_config", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap p_32_log_config {
            get {
                object obj = ResourceManager.GetObject("p_32_log_config", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap p_48_bug_mail {
            get {
                object obj = ResourceManager.GetObject("p_48_bug_mail", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap p_48_forbidden {
            get {
                object obj = ResourceManager.GetObject("p_48_forbidden", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap p_48_ok {
            get {
                object obj = ResourceManager.GetObject("p_48_ok", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap p_48_question {
            get {
                object obj = ResourceManager.GetObject("p_48_question", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap p_48_stop {
            get {
                object obj = ResourceManager.GetObject("p_48_stop", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap p_48_user_error {
            get {
                object obj = ResourceManager.GetObject("p_48_user_error", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Restart on critical Error.
        /// </summary>
        public static string RESTART_ON_CRITICAL {
            get {
                return ResourceManager.GetString("RESTART_ON_CRITICAL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Retry.
        /// </summary>
        public static string RETRY {
            get {
                return ResourceManager.GetString("RETRY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Application settings.
        /// </summary>
        public static string SETTINGS {
            get {
                return ResourceManager.GetString("SETTINGS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Generic settings.
        /// </summary>
        public static string SETTINGS_GENERIC {
            get {
                return ResourceManager.GetString("SETTINGS_GENERIC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log display settings.
        /// </summary>
        public static string SETTINGS_LOG_DISPLAY {
            get {
                return ResourceManager.GetString("SETTINGS_LOG_DISPLAY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show debug messages.
        /// </summary>
        public static string SETTINGS_LOG_DISPLAY_DEBUG_COLOR {
            get {
                return ResourceManager.GetString("SETTINGS_LOG_DISPLAY_DEBUG_COLOR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        public static string SETTINGS_LOG_DISPLAY_ERROR_COLOR {
            get {
                return ResourceManager.GetString("SETTINGS_LOG_DISPLAY_ERROR_COLOR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Info.
        /// </summary>
        public static string SETTINGS_LOG_DISPLAY_INFO_COLOR {
            get {
                return ResourceManager.GetString("SETTINGS_LOG_DISPLAY_INFO_COLOR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warining.
        /// </summary>
        public static string SETTINGS_LOG_DISPLAY_WARN_COLOR {
            get {
                return ResourceManager.GetString("SETTINGS_LOG_DISPLAY_WARN_COLOR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recent count.
        /// </summary>
        public static string SETTINGS_LOG_RECENT_COUNT {
            get {
                return ResourceManager.GetString("SETTINGS_LOG_RECENT_COUNT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Restart.
        /// </summary>
        public static string SETTINGS_RESTART_TITLE {
            get {
                return ResourceManager.GetString("SETTINGS_RESTART_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Some of the changes made require restart of the application. Do you want to restart now?.
        /// </summary>
        public static string SETTINGS_RESTART_WARNING {
            get {
                return ResourceManager.GetString("SETTINGS_RESTART_WARNING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Validate.
        /// </summary>
        public static string SETTINGS_VALIDATE {
            get {
                return ResourceManager.GetString("SETTINGS_VALIDATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status.
        /// </summary>
        public static string STATUS {
            get {
                return ResourceManager.GetString("STATUS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Some critical errors leaded to stop. View detail descripton for all messages to explain.
        /// </summary>
        public static string SUMMARY_ERROR {
            get {
                return ResourceManager.GetString("SUMMARY_ERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to These messages contain only information and does not require anithing to do.
        /// </summary>
        public static string SUMMARY_INFO {
            get {
                return ResourceManager.GetString("SUMMARY_INFO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Read these warnings and fix the problems detected.
        /// </summary>
        public static string SUMMARY_WARNING {
            get {
                return ResourceManager.GetString("SUMMARY_WARNING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Task.
        /// </summary>
        public static string TASK {
            get {
                return ResourceManager.GetString("TASK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This task does not provide results.
        /// </summary>
        public static string TASK_NO_RESULT {
            get {
                return ResourceManager.GetString("TASK_NO_RESULT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to State.
        /// </summary>
        public static string TASK_STATE {
            get {
                return ResourceManager.GetString("TASK_STATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unexpected cancellation by user.
        /// </summary>
        public static string UNEXPECTED_CANCELLATION_BY_USER {
            get {
                return ResourceManager.GetString("UNEXPECTED_CANCELLATION_BY_USER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown action.
        /// </summary>
        public static string UNKNOWN_ACTION {
            get {
                return ResourceManager.GetString("UNKNOWN_ACTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Updating of the program.
        /// </summary>
        public static string UPDATING_OF_THE_PROGRAM {
            get {
                return ResourceManager.GetString("UPDATING_OF_THE_PROGRAM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Version.
        /// </summary>
        public static string VERSION_TITLE {
            get {
                return ResourceManager.GetString("VERSION_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warings.
        /// </summary>
        public static string WARNINGS_COUNT {
            get {
                return ResourceManager.GetString("WARNINGS_COUNT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes.
        /// </summary>
        public static string YES {
            get {
                return ResourceManager.GetString("YES", resourceCulture);
            }
        }
    }
}
