//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.18444
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Toolbox.Properties {
    using System;
    
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте свой проект VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Toolbox.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Перезаписывает свойство CurrentUICulture текущего потока для всех
        ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Cancelled.
        /// </summary>
        internal static string CANCELLED {
            get {
                return ResourceManager.GetString("CANCELLED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Cancelling.
        /// </summary>
        internal static string CANCELLING {
            get {
                return ResourceManager.GetString("CANCELLING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Completed.
        /// </summary>
        internal static string COMPLETED {
            get {
                return ResourceManager.GetString("COMPLETED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Error while configuring application. Config file may be damaged. Setting default values.
        /// </summary>
        internal static string CONFIG_ERROR_FILE {
            get {
                return ResourceManager.GetString("CONFIG_ERROR_FILE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Failure saving config..
        /// </summary>
        internal static string CONFIG_ERROR_SAVE {
            get {
                return ResourceManager.GetString("CONFIG_ERROR_SAVE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на No valid config file.
        /// </summary>
        internal static string CONFIG_NO_FILE {
            get {
                return ResourceManager.GetString("CONFIG_NO_FILE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Only one application instance is allowed.
        /// </summary>
        internal static string CONFIG_NO_INSTANCE {
            get {
                return ResourceManager.GetString("CONFIG_NO_INSTANCE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на No config file found, setting default values..
        /// </summary>
        internal static string CONFIG_WARNING_FILE {
            get {
                return ResourceManager.GetString("CONFIG_WARNING_FILE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на parameterNameGetter throws exception.
        /// </summary>
        internal static string ConvertionHelper_GetNullException_parameterNameGetterThrowsException {
            get {
                return ResourceManager.GetString("ConvertionHelper_GetNullException_parameterNameGetterThrowsException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Converter for {0}.
        /// </summary>
        internal static string ConvertionHelper_ToString_Format {
            get {
                return ResourceManager.GetString("ConvertionHelper_ToString_Format", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Language standard: {0}, value: {1}.
        /// </summary>
        internal static string DetalizedFormatException_Message_Format {
            get {
                return ResourceManager.GetString("DetalizedFormatException_Message_Format", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Error.
        /// </summary>
        internal static string ERROR {
            get {
                return ResourceManager.GetString("ERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на {1}{0}File name: &apos;{2}&apos;.
        /// </summary>
        internal static string FileNotFoundDetalizedException_Message_format {
            get {
                return ResourceManager.GetString("FileNotFoundDetalizedException_Message_format", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Failed acquiring MainModule.
        /// </summary>
        internal static string INIT_NO_MODULE {
            get {
                return ResourceManager.GetString("INIT_NO_MODULE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Configuration section must be a non-abstract class with paramrterless constructor and inherited from Toolbox.Configuration.ConfigurationSection.
        /// </summary>
        internal static string INVALID_CONFIG_SECTION_TYPE {
            get {
                return ResourceManager.GetString("INVALID_CONFIG_SECTION_TYPE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Delegate type {0} is not recognized as EventHandler&lt;{1}&gt;.
        /// </summary>
        internal static string INVALID_EVENT_HANDLER {
            get {
                return ResourceManager.GetString("INVALID_EVENT_HANDLER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на {0} has invalid value of the property {1}.
        /// </summary>
        internal static string INVALID_LOOKUP_PROPERTY {
            get {
                return ResourceManager.GetString("INVALID_LOOKUP_PROPERTY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot; ?&gt;
        ///&lt;log4net&gt;
        ///	&lt;appender name=&quot;MainAppender&quot; type=&quot;log4net.Appender.RollingFileAppender&quot;&gt;
        ///		&lt;file type=&quot;log4net.Util.PatternString&quot; value=&quot;%property{appDataDir}/Logs/%property{appName}.log&quot; /&gt;
        ///		&lt;lockingModel type=&quot;log4net.Appender.FileAppender+MinimalLock&quot; /&gt;
        ///		&lt;appendToFile value=&quot;true&quot; /&gt;
        ///		&lt;encoding value=&quot;utf-8&quot; /&gt;
        ///		&lt;rollingStyle value=&quot;Size&quot; /&gt;
        ///		&lt;maxSizeRollBackups value=&quot;10&quot; /&gt;
        ///		&lt;maximumFileSize value=&quot;5MB&quot; /&gt;
        ///		&lt;PreserveLogFileNameExtension value=&quot;tru [остаток строки не уместился]&quot;;.
        /// </summary>
        internal static string Log4netConfig {
            get {
                return ResourceManager.GetString("Log4netConfig", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Lookup for the type {0} is not parametrized.
        /// </summary>
        internal static string LOOKUP_NO_PARAMS {
            get {
                return ResourceManager.GetString("LOOKUP_NO_PARAMS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Lookup type {0} must be set up before using.
        /// </summary>
        internal static string LOOKUP_NOT_SET {
            get {
                return ResourceManager.GetString("LOOKUP_NOT_SET", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Cannot clone empty gradient.
        /// </summary>
        internal static string MSG_CANNOT_CLONE_EMPTY_GRADIENT {
            get {
                return ResourceManager.GetString("MSG_CANNOT_CLONE_EMPTY_GRADIENT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Pending.
        /// </summary>
        internal static string PENDING {
            get {
                return ResourceManager.GetString("PENDING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Plug-in {0} successfullty loaded.
        /// </summary>
        internal static string PLUGIN_LOADED {
            get {
                return ResourceManager.GetString("PLUGIN_LOADED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Property &apos;{0}&apos; value changed: from {1} to {2}.
        /// </summary>
        internal static string PROPERTY_CHANGED {
            get {
                return ResourceManager.GetString("PROPERTY_CHANGED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Running.
        /// </summary>
        internal static string RUNNING {
            get {
                return ResourceManager.GetString("RUNNING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Results of task work.
        /// </summary>
        internal static string TASK_RESULT {
            get {
                return ResourceManager.GetString("TASK_RESULT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Internal work fault detected. See inner exception for details.
        /// </summary>
        internal static string WORK_FAULT {
            get {
                return ResourceManager.GetString("WORK_FAULT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Wrong parameter type description.
        /// </summary>
        internal static string WRONG_PARAMETER_TYPE_DESCRIPTION {
            get {
                return ResourceManager.GetString("WRONG_PARAMETER_TYPE_DESCRIPTION", resourceCulture);
            }
        }
    }
}
