//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.237
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ATHelpEditor.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ATHelpEditor.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        public static System.Drawing.Bitmap _16_book {
            get {
                object obj = ResourceManager.GetObject("16_book", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap _16_book_open {
            get {
                object obj = ResourceManager.GetObject("16_book_open", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap _16_help {
            get {
                object obj = ResourceManager.GetObject("16_help", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap _16_pin_blue {
            get {
                object obj = ResourceManager.GetObject("16_pin_blue", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap _24_book_blue_add {
            get {
                object obj = ResourceManager.GetObject("24_book_blue_add", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap _24_book_blue_delete {
            get {
                object obj = ResourceManager.GetObject("24_book_blue_delete", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap _24_hyperlink_add {
            get {
                object obj = ResourceManager.GetObject("24_hyperlink_add", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap _24_open {
            get {
                object obj = ResourceManager.GetObject("24_open", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap _24_picture {
            get {
                object obj = ResourceManager.GetObject("24_picture", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap _24_pin_blue {
            get {
                object obj = ResourceManager.GetObject("24_pin_blue", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap _24_save {
            get {
                object obj = ResourceManager.GetObject("24_save", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap _24_text_align_center {
            get {
                object obj = ResourceManager.GetObject("24_text_align_center", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap _24_text_align_justified {
            get {
                object obj = ResourceManager.GetObject("24_text_align_justified", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap _24_text_align_left {
            get {
                object obj = ResourceManager.GetObject("24_text_align_left", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap _24_text_align_right {
            get {
                object obj = ResourceManager.GetObject("24_text_align_right", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap _24_text_bold {
            get {
                object obj = ResourceManager.GetObject("24_text_bold", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap _24_text_indent {
            get {
                object obj = ResourceManager.GetObject("24_text_indent", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap _24_text_italics {
            get {
                object obj = ResourceManager.GetObject("24_text_italics", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap _24_text_outdent {
            get {
                object obj = ResourceManager.GetObject("24_text_outdent", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap _24_text_underlined {
            get {
                object obj = ResourceManager.GetObject("24_text_underlined", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap _48_help {
            get {
                object obj = ResourceManager.GetObject("48_help", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap _48_hyperlink_add {
            get {
                object obj = ResourceManager.GetObject("48_hyperlink_add", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap _48_pin_blue {
            get {
                object obj = ResourceManager.GetObject("48_pin_blue", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alignment.
        /// </summary>
        public static string ADDSTYLE_ALIGNMENT {
            get {
                return ResourceManager.GetString("ADDSTYLE_ALIGNMENT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Color.
        /// </summary>
        public static string ADDSTYLE_COLOR {
            get {
                return ResourceManager.GetString("ADDSTYLE_COLOR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Demo.
        /// </summary>
        public static string ADDSTYLE_DEMO {
            get {
                return ResourceManager.GetString("ADDSTYLE_DEMO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Duplicate names of the style.
        /// </summary>
        public static string ADDSTYLE_DUPLICATENAME {
            get {
                return ResourceManager.GetString("ADDSTYLE_DUPLICATENAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Font.
        /// </summary>
        public static string ADDSTYLE_FONT {
            get {
                return ResourceManager.GetString("ADDSTYLE_FONT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Font size.
        /// </summary>
        public static string ADDSTYLE_FONTSIZE {
            get {
                return ResourceManager.GetString("ADDSTYLE_FONTSIZE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string ADDSTYLE_NAME {
            get {
                return ResourceManager.GetString("ADDSTYLE_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The name of the style is not set.
        /// </summary>
        public static string ADDSTYLE_NONAME {
            get {
                return ResourceManager.GetString("ADDSTYLE_NONAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Center.
        /// </summary>
        public static string ALIGNMENT_CENTER {
            get {
                return ResourceManager.GetString("ALIGNMENT_CENTER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Default.
        /// </summary>
        public static string ALIGNMENT_DEFAULT {
            get {
                return ResourceManager.GetString("ALIGNMENT_DEFAULT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Far.
        /// </summary>
        public static string ALIGNMENT_FAR {
            get {
                return ResourceManager.GetString("ALIGNMENT_FAR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Near.
        /// </summary>
        public static string ALIGNMENT_NEAR {
            get {
                return ResourceManager.GetString("ALIGNMENT_NEAR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string BUTTON_CANCEL {
            get {
                return ResourceManager.GetString("BUTTON_CANCEL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        public static string BUTTON_OK {
            get {
                return ResourceManager.GetString("BUTTON_OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Document fromat properties.
        /// </summary>
        public static string DOC_PROPERTIES {
            get {
                return ResourceManager.GetString("DOC_PROPERTIES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Background color.
        /// </summary>
        public static string DOC_PROPERTIES_BG_COLOR {
            get {
                return ResourceManager.GetString("DOC_PROPERTIES_BG_COLOR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Color.
        /// </summary>
        public static string DOC_PROPERTIES_COLOR {
            get {
                return ResourceManager.GetString("DOC_PROPERTIES_COLOR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Active link color.
        /// </summary>
        public static string DOC_PROPERTIES_COLOR_ALINK {
            get {
                return ResourceManager.GetString("DOC_PROPERTIES_COLOR_ALINK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Link color.
        /// </summary>
        public static string DOC_PROPERTIES_COLOR_LINK {
            get {
                return ResourceManager.GetString("DOC_PROPERTIES_COLOR_LINK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Visited link color.
        /// </summary>
        public static string DOC_PROPERTIES_COLOR_VLINK {
            get {
                return ResourceManager.GetString("DOC_PROPERTIES_COLOR_VLINK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Foreground color.
        /// </summary>
        public static string DOC_PROPERTIES_FORE_COLOR {
            get {
                return ResourceManager.GetString("DOC_PROPERTIES_FORE_COLOR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Margin.
        /// </summary>
        public static string DOC_PROPERTIES_MARGIN {
            get {
                return ResourceManager.GetString("DOC_PROPERTIES_MARGIN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bottom margin.
        /// </summary>
        public static string DOC_PROPERTIES_MARGIN_BOTTOM {
            get {
                return ResourceManager.GetString("DOC_PROPERTIES_MARGIN_BOTTOM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Margin height.
        /// </summary>
        public static string DOC_PROPERTIES_MARGIN_HEIGHT {
            get {
                return ResourceManager.GetString("DOC_PROPERTIES_MARGIN_HEIGHT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Left margin.
        /// </summary>
        public static string DOC_PROPERTIES_MARGIN_LEFT {
            get {
                return ResourceManager.GetString("DOC_PROPERTIES_MARGIN_LEFT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Margin properties.
        /// </summary>
        public static string DOC_PROPERTIES_MARGIN_PROP {
            get {
                return ResourceManager.GetString("DOC_PROPERTIES_MARGIN_PROP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Right margin.
        /// </summary>
        public static string DOC_PROPERTIES_MARGIN_RIGHT {
            get {
                return ResourceManager.GetString("DOC_PROPERTIES_MARGIN_RIGHT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Top margin.
        /// </summary>
        public static string DOC_PROPERTIES_MARGIN_TOP {
            get {
                return ResourceManager.GetString("DOC_PROPERTIES_MARGIN_TOP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Margin width.
        /// </summary>
        public static string DOC_PROPERTIES_MARGIN_WIDTH {
            get {
                return ResourceManager.GetString("DOC_PROPERTIES_MARGIN_WIDTH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Compile.
        /// </summary>
        public static string MF_COMPILE {
            get {
                return ResourceManager.GetString("MF_COMPILE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Compile and test.
        /// </summary>
        public static string MF_COMPILE_TEST {
            get {
                return ResourceManager.GetString("MF_COMPILE_TEST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log.
        /// </summary>
        public static string MF_LOG {
            get {
                return ResourceManager.GetString("MF_LOG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Project.
        /// </summary>
        public static string MF_NEW_PROJECT {
            get {
                return ResourceManager.GetString("MF_NEW_PROJECT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Help File Nodes.
        /// </summary>
        public static string MF_NODES {
            get {
                return ResourceManager.GetString("MF_NODES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open Project.
        /// </summary>
        public static string MF_OPEN_PROJECT {
            get {
                return ResourceManager.GetString("MF_OPEN_PROJECT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save all.
        /// </summary>
        public static string MF_SAVE_ALL {
            get {
                return ResourceManager.GetString("MF_SAVE_ALL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save project.
        /// </summary>
        public static string MF_SAVE_PROJECT {
            get {
                return ResourceManager.GetString("MF_SAVE_PROJECT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        public static string MF_SETTINGS {
            get {
                return ResourceManager.GetString("MF_SETTINGS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There are unsaved changes in the file. Would you like to save it now ?.
        /// </summary>
        public static string MODIFIED_FILES {
            get {
                return ResourceManager.GetString("MODIFIED_FILES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your project has been changed. Would you like to save it now ?.
        /// </summary>
        public static string MODIFIED_PROJECT {
            get {
                return ResourceManager.GetString("MODIFIED_PROJECT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        public static string NAVIGATOR_DELETE {
            get {
                return ResourceManager.GetString("NAVIGATOR_DELETE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Display name.
        /// </summary>
        public static string NAVIGATOR_DISPLAY_NAME {
            get {
                return ResourceManager.GetString("NAVIGATOR_DISPLAY_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ID.
        /// </summary>
        public static string NAVIGATOR_ID {
            get {
                return ResourceManager.GetString("NAVIGATOR_ID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Import.
        /// </summary>
        public static string NAVIGATOR_IMPORT {
            get {
                return ResourceManager.GetString("NAVIGATOR_IMPORT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Import project.
        /// </summary>
        public static string NAVIGATOR_IMPORT_PROJECT {
            get {
                return ResourceManager.GetString("NAVIGATOR_IMPORT_PROJECT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New help topic.
        /// </summary>
        public static string NAVIGATOR_NEW_HELP_TOPIC {
            get {
                return ResourceManager.GetString("NAVIGATOR_NEW_HELP_TOPIC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error while opening the project.
        /// </summary>
        public static string PROJECT_ERROR {
            get {
                return ResourceManager.GetString("PROJECT_ERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Empty project.
        /// </summary>
        public static string PROJECT_ERROR_EMPTY {
            get {
                return ResourceManager.GetString("PROJECT_ERROR_EMPTY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Help Editor.
        /// </summary>
        public static string SETTINGS_PAGE_GROUP {
            get {
                return ResourceManager.GetString("SETTINGS_PAGE_GROUP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hrlp Editor properties.
        /// </summary>
        public static string SETTINGS_PAGE_NAME {
            get {
                return ResourceManager.GetString("SETTINGS_PAGE_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Template path.
        /// </summary>
        public static string SETTINGS_PAGE_PATH {
            get {
                return ResourceManager.GetString("SETTINGS_PAGE_PATH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Topic edit form.
        /// </summary>
        public static string TOPIC_EDITOR {
            get {
                return ResourceManager.GetString("TOPIC_EDITOR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Topic Id.
        /// </summary>
        public static string TOPIC_EDITOR_ID {
            get {
                return ResourceManager.GetString("TOPIC_EDITOR_ID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Topic name.
        /// </summary>
        public static string TOPIC_EDITOR_NAME {
            get {
                return ResourceManager.GetString("TOPIC_EDITOR_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unsaved changes!.
        /// </summary>
        public static string UNSAVED_CHANGES {
            get {
                return ResourceManager.GetString("UNSAVED_CHANGES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to URI Editor.
        /// </summary>
        public static string URI_EDITOR {
            get {
                return ResourceManager.GetString("URI_EDITOR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy locally.
        /// </summary>
        public static string URI_EDITOR_COPY {
            get {
                return ResourceManager.GetString("URI_EDITOR_COPY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Index.
        /// </summary>
        public static string URI_EDITOR_INDEX {
            get {
                return ResourceManager.GetString("URI_EDITOR_INDEX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string URI_EDITOR_NAME {
            get {
                return ResourceManager.GetString("URI_EDITOR_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File or page.
        /// </summary>
        public static string URI_EDITOR_RESOURCE {
            get {
                return ResourceManager.GetString("URI_EDITOR_RESOURCE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Topic.
        /// </summary>
        public static string URI_EDITOR_TOPIC {
            get {
                return ResourceManager.GetString("URI_EDITOR_TOPIC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warning.
        /// </summary>
        public static string WARNING {
            get {
                return ResourceManager.GetString("WARNING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Align center.
        /// </summary>
        public static string WISIWYG_ALIGN_CENTER {
            get {
                return ResourceManager.GetString("WISIWYG_ALIGN_CENTER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Align justify.
        /// </summary>
        public static string WISIWYG_ALIGN_JUSTIFY {
            get {
                return ResourceManager.GetString("WISIWYG_ALIGN_JUSTIFY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Align left.
        /// </summary>
        public static string WISIWYG_ALIGN_LEFT {
            get {
                return ResourceManager.GetString("WISIWYG_ALIGN_LEFT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Align right.
        /// </summary>
        public static string WISIWYG_ALIGN_RIGHT {
            get {
                return ResourceManager.GetString("WISIWYG_ALIGN_RIGHT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Back color.
        /// </summary>
        public static string WISIWYG_BACK_COLOR {
            get {
                return ResourceManager.GetString("WISIWYG_BACK_COLOR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Color.
        /// </summary>
        public static string WISIWYG_BAR_COLOR {
            get {
                return ResourceManager.GetString("WISIWYG_BAR_COLOR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File.
        /// </summary>
        public static string WISIWYG_BAR_FILE {
            get {
                return ResourceManager.GetString("WISIWYG_BAR_FILE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Font.
        /// </summary>
        public static string WISIWYG_BAR_FONT {
            get {
                return ResourceManager.GetString("WISIWYG_BAR_FONT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Format.
        /// </summary>
        public static string WISIWYG_BAR_FORMAT {
            get {
                return ResourceManager.GetString("WISIWYG_BAR_FORMAT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tools.
        /// </summary>
        public static string WISIWYG_BAR_TOOLS {
            get {
                return ResourceManager.GetString("WISIWYG_BAR_TOOLS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bold.
        /// </summary>
        public static string WISIWYG_BOLD {
            get {
                return ResourceManager.GetString("WISIWYG_BOLD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Source code.
        /// </summary>
        public static string WISIWYG_CODE {
            get {
                return ResourceManager.GetString("WISIWYG_CODE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Designer.
        /// </summary>
        public static string WISIWYG_DESIGNER {
            get {
                return ResourceManager.GetString("WISIWYG_DESIGNER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Font.
        /// </summary>
        public static string WISIWYG_FONT {
            get {
                return ResourceManager.GetString("WISIWYG_FONT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Font size.
        /// </summary>
        public static string WISIWYG_FONT_SIZE {
            get {
                return ResourceManager.GetString("WISIWYG_FONT_SIZE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fore color.
        /// </summary>
        public static string WISIWYG_FORE_COLOR {
            get {
                return ResourceManager.GetString("WISIWYG_FORE_COLOR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Indent.
        /// </summary>
        public static string WISIWYG_INDENT {
            get {
                return ResourceManager.GetString("WISIWYG_INDENT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Insert bookmark.
        /// </summary>
        public static string WISIWYG_INSERT_BOOKMARK {
            get {
                return ResourceManager.GetString("WISIWYG_INSERT_BOOKMARK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Insert horizontal line.
        /// </summary>
        public static string WISIWYG_INSERT_HR {
            get {
                return ResourceManager.GetString("WISIWYG_INSERT_HR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Insert image.
        /// </summary>
        public static string WISIWYG_INSERT_IMAGE {
            get {
                return ResourceManager.GetString("WISIWYG_INSERT_IMAGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Insert link.
        /// </summary>
        public static string WISIWYG_INSERT_LINK {
            get {
                return ResourceManager.GetString("WISIWYG_INSERT_LINK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Insert ordered list.
        /// </summary>
        public static string WISIWYG_INSERT_OL {
            get {
                return ResourceManager.GetString("WISIWYG_INSERT_OL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Insert unsorted list.
        /// </summary>
        public static string WISIWYG_INSERT_UL {
            get {
                return ResourceManager.GetString("WISIWYG_INSERT_UL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Italic.
        /// </summary>
        public static string WISIWYG_ITALIC {
            get {
                return ResourceManager.GetString("WISIWYG_ITALIC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Properties.
        /// </summary>
        public static string WISIWYG_PROPERTIES {
            get {
                return ResourceManager.GetString("WISIWYG_PROPERTIES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string WISIWYG_SAVE {
            get {
                return ResourceManager.GetString("WISIWYG_SAVE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Underline.
        /// </summary>
        public static string WISIWYG_UNDERLINE {
            get {
                return ResourceManager.GetString("WISIWYG_UNDERLINE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unindent.
        /// </summary>
        public static string WISIWYG_UNINDENT {
            get {
                return ResourceManager.GetString("WISIWYG_UNINDENT", resourceCulture);
            }
        }
    }
}
