//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.237
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AT.Toolbox.MSSQL.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AT.Toolbox.MSSQL.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Apply.
        /// </summary>
        internal static string APPLY {
            get {
                return ResourceManager.GetString("APPLY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Audio editor path.
        /// </summary>
        internal static string AudioEditorPath {
            get {
                return ResourceManager.GetString("AudioEditorPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Call of the reader operation can cause cache corruption. .
        /// </summary>
        internal static string BindableObject_CacheCorruption {
            get {
                return ResourceManager.GetString("BindableObject_CacheCorruption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Method {0} is invalid for the complex primary key.
        /// </summary>
        internal static string BindableObject_ComplexPK_Error {
            get {
                return ResourceManager.GetString("BindableObject_ComplexPK_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BindableObject_DirectFieldAccess.
        /// </summary>
        internal static string BindableObject_DirectFieldAccess {
            get {
                return ResourceManager.GetString("BindableObject_DirectFieldAccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BindableObject_ExtendedAspect.
        /// </summary>
        internal static string BindableObject_ExtendedAspect {
            get {
                return ResourceManager.GetString("BindableObject_ExtendedAspect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Foreign key for {0} not found.
        /// </summary>
        internal static string BindableObject_FK_NotFound {
            get {
                return ResourceManager.GetString("BindableObject_FK_NotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Foreign key value {0} is invalid.
        /// </summary>
        internal static string BindableObject_IncorrectForeignKey {
            get {
                return ResourceManager.GetString("BindableObject_IncorrectForeignKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BindableObject_NoAccess.
        /// </summary>
        internal static string BindableObject_NoAccess {
            get {
                return ResourceManager.GetString("BindableObject_NoAccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attempt of (BindableObject.Orig) editing.
        /// </summary>
        internal static string BindableObject_OrigEdit {
            get {
                return ResourceManager.GetString("BindableObject_OrigEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Property for the access to the field {0} not found.
        /// </summary>
        internal static string BindableObject_PropertyNotFound {
            get {
                return ResourceManager.GetString("BindableObject_PropertyNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BindableObject_RecursiveAspectCall.
        /// </summary>
        internal static string BindableObject_RecursiveAspectCall {
            get {
                return ResourceManager.GetString("BindableObject_RecursiveAspectCall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to delete record form {0}. There are related records in {1}.
        /// </summary>
        internal static string BindableObject_RestrictedTrigger {
            get {
                return ResourceManager.GetString("BindableObject_RestrictedTrigger", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parent list is not set.
        /// </summary>
        internal static string BindableObjectList_NullParent {
            get {
                return ResourceManager.GetString("BindableObjectList_NullParent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Building mould.
        /// </summary>
        internal static string BUILD_MOULD {
            get {
                return ResourceManager.GetString("BUILD_MOULD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Incorrect version: it must be larger than old version.
        /// </summary>
        internal static string BUILD_MOULD_INCORRECT_VERSION {
            get {
                return ResourceManager.GetString("BUILD_MOULD_INCORRECT_VERSION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New mould.
        /// </summary>
        internal static string BUILD_MOULD_NEW_MOULD {
            get {
                return ResourceManager.GetString("BUILD_MOULD_NEW_MOULD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New version.
        /// </summary>
        internal static string BUILD_MOULD_NEW_VERSION {
            get {
                return ResourceManager.GetString("BUILD_MOULD_NEW_VERSION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mould path is not selected.
        /// </summary>
        internal static string BUILD_MOULD_NO_PATH {
            get {
                return ResourceManager.GetString("BUILD_MOULD_NO_PATH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Old mould.
        /// </summary>
        internal static string BUILD_MOULD_OLD_MOULD {
            get {
                return ResourceManager.GetString("BUILD_MOULD_OLD_MOULD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Old version.
        /// </summary>
        internal static string BUILD_MOULD_OLD_VERSION {
            get {
                return ResourceManager.GetString("BUILD_MOULD_OLD_VERSION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Refreshing database.
        /// </summary>
        internal static string BUILD_MOULD_REFRESH_DATABASE {
            get {
                return ResourceManager.GetString("BUILD_MOULD_REFRESH_DATABASE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Refreshing metadata.
        /// </summary>
        internal static string BUILD_MOULD_REFRESH_METADATA {
            get {
                return ResourceManager.GetString("BUILD_MOULD_REFRESH_METADATA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        internal static string CANCEL {
            get {
                return ResourceManager.GetString("CANCEL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear log.
        /// </summary>
        internal static string CLEAR_LOG {
            get {
                return ResourceManager.GetString("CLEAR_LOG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to connect to server. Do you want to check connection?.
        /// </summary>
        internal static string CONTEXT_CONNECTION_FAILED {
            get {
                return ResourceManager.GetString("CONTEXT_CONNECTION_FAILED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Server connection completed successfully.
        /// </summary>
        internal static string CONTEXT_CONNECTION_OK {
            get {
                return ResourceManager.GetString("CONTEXT_CONNECTION_OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error working with database context.
        /// </summary>
        internal static string ContextException {
            get {
                return ResourceManager.GetString("ContextException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to replace type supporting custom record binding.
        /// </summary>
        internal static string CUSTOM_BINDER_TO_REPLACE {
            get {
                return ResourceManager.GetString("CUSTOM_BINDER_TO_REPLACE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Database.
        /// </summary>
        internal static string DATABASE {
            get {
                return ResourceManager.GetString("DATABASE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add new database.
        /// </summary>
        internal static string DB_BROWSER_ADD_DATABASE {
            get {
                return ResourceManager.GetString("DB_BROWSER_ADD_DATABASE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add database.
        /// </summary>
        internal static string DB_BROWSER_ADD_DB {
            get {
                return ResourceManager.GetString("DB_BROWSER_ADD_DB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add new database.
        /// </summary>
        internal static string DB_BROWSER_ADD_DB_TIP {
            get {
                return ResourceManager.GetString("DB_BROWSER_ADD_DB_TIP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Server.
        /// </summary>
        internal static string DB_BROWSER_ADD_SERVER {
            get {
                return ResourceManager.GetString("DB_BROWSER_ADD_SERVER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adds MS SQL server to the list.
        /// </summary>
        internal static string DB_BROWSER_ADD_SERVER_TIP {
            get {
                return ResourceManager.GetString("DB_BROWSER_ADD_SERVER_TIP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Backup.
        /// </summary>
        internal static string DB_BROWSER_BACKUP {
            get {
                return ResourceManager.GetString("DB_BROWSER_BACKUP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Backup selected database.
        /// </summary>
        internal static string DB_BROWSER_BACKUP_TIP {
            get {
                return ResourceManager.GetString("DB_BROWSER_BACKUP_TIP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Database name.
        /// </summary>
        internal static string DB_BROWSER_COL_NAME {
            get {
                return ResourceManager.GetString("DB_BROWSER_COL_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status.
        /// </summary>
        internal static string DB_BROWSER_COL_STATUS {
            get {
                return ResourceManager.GetString("DB_BROWSER_COL_STATUS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Test results.
        /// </summary>
        internal static string DB_BROWSER_COL_TEST_RESULTS {
            get {
                return ResourceManager.GetString("DB_BROWSER_COL_TEST_RESULTS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Used.
        /// </summary>
        internal static string DB_BROWSER_COL_USED {
            get {
                return ResourceManager.GetString("DB_BROWSER_COL_USED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Version.
        /// </summary>
        internal static string DB_BROWSER_COL_VERSION {
            get {
                return ResourceManager.GetString("DB_BROWSER_COL_VERSION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Convert data types date and time for compatibility.
        /// </summary>
        internal static string DB_BROWSER_COMPATIBILITY_MODE_MS_SQL_SERVER_2005 {
            get {
                return ResourceManager.GetString("DB_BROWSER_COMPATIBILITY_MODE_MS_SQL_SERVER_2005", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Continue to create the DB structure for errors in scripts.
        /// </summary>
        internal static string DB_BROWSER_CONTINUE_ON_ERROR_IN_SCRIPTS {
            get {
                return ResourceManager.GetString("DB_BROWSER_CONTINUE_ON_ERROR_IN_SCRIPTS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Import data.
        /// </summary>
        internal static string DB_BROWSER_IMPORT_DATA {
            get {
                return ResourceManager.GetString("DB_BROWSER_IMPORT_DATA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Import data complete.
        /// </summary>
        internal static string DB_BROWSER_IMPORT_DATA_COMPLETE {
            get {
                return ResourceManager.GetString("DB_BROWSER_IMPORT_DATA_COMPLETE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Import data by selected algorithm.
        /// </summary>
        internal static string DB_BROWSER_IMPORT_DATA_TIP {
            get {
                return ResourceManager.GetString("DB_BROWSER_IMPORT_DATA_TIP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mould.
        /// </summary>
        internal static string DB_BROWSER_MOULD {
            get {
                return ResourceManager.GetString("DB_BROWSER_MOULD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Build the mould of the selected database.
        /// </summary>
        internal static string DB_BROWSER_MOULD_TIP {
            get {
                return ResourceManager.GetString("DB_BROWSER_MOULD_TIP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Only network path can be used for backup.
        /// </summary>
        internal static string DB_BROWSER_ONLY_UNC {
            get {
                return ResourceManager.GetString("DB_BROWSER_ONLY_UNC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Perform backup.
        /// </summary>
        internal static string DB_BROWSER_PERFORM_BACKUP {
            get {
                return ResourceManager.GetString("DB_BROWSER_PERFORM_BACKUP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recreate tables.
        /// </summary>
        internal static string DB_BROWSER_RECREATE_TABLES {
            get {
                return ResourceManager.GetString("DB_BROWSER_RECREATE_TABLES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Refresh all.
        /// </summary>
        internal static string DB_BROWSER_REFRESH_ALL {
            get {
                return ResourceManager.GetString("DB_BROWSER_REFRESH_ALL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Refreshes database list for all servers.
        /// </summary>
        internal static string DB_BROWSER_REFRESH_ALL_TIP {
            get {
                return ResourceManager.GetString("DB_BROWSER_REFRESH_ALL_TIP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Refresh Server Info.
        /// </summary>
        internal static string DB_BROWSER_REFRESH_SERVER {
            get {
                return ResourceManager.GetString("DB_BROWSER_REFRESH_SERVER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Refresh databases on the current server.
        /// </summary>
        internal static string DB_BROWSER_REFRESH_SERVER_TIP {
            get {
                return ResourceManager.GetString("DB_BROWSER_REFRESH_SERVER_TIP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove database.
        /// </summary>
        internal static string DB_BROWSER_REMOVE_DB {
            get {
                return ResourceManager.GetString("DB_BROWSER_REMOVE_DB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure to physically remove database.
        /// </summary>
        internal static string DB_BROWSER_REMOVE_DB_CONFIRM {
            get {
                return ResourceManager.GetString("DB_BROWSER_REMOVE_DB_CONFIRM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove selected database.
        /// </summary>
        internal static string DB_BROWSER_REMOVE_DB_TIP {
            get {
                return ResourceManager.GetString("DB_BROWSER_REMOVE_DB_TIP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove server.
        /// </summary>
        internal static string DB_BROWSER_REMOVE_SERVER {
            get {
                return ResourceManager.GetString("DB_BROWSER_REMOVE_SERVER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Removes selected server from the list.
        /// </summary>
        internal static string DB_BROWSER_REMOVE_SERVER_TIP {
            get {
                return ResourceManager.GetString("DB_BROWSER_REMOVE_SERVER_TIP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset database.
        /// </summary>
        internal static string DB_BROWSER_RESET_DB {
            get {
                return ResourceManager.GetString("DB_BROWSER_RESET_DB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset selected database.
        /// </summary>
        internal static string DB_BROWSER_RESET_DB_TIP {
            get {
                return ResourceManager.GetString("DB_BROWSER_RESET_DB_TIP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Restore.
        /// </summary>
        internal static string DB_BROWSER_RESTORE {
            get {
                return ResourceManager.GetString("DB_BROWSER_RESTORE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Restore selected database.
        /// </summary>
        internal static string DB_BROWSER_RESTORE_TIP {
            get {
                return ResourceManager.GetString("DB_BROWSER_RESTORE_TIP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Run script.
        /// </summary>
        internal static string DB_BROWSER_RUN_SCRIPT {
            get {
                return ResourceManager.GetString("DB_BROWSER_RUN_SCRIPT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open SQL file and run it.
        /// </summary>
        internal static string DB_BROWSER_RUN_SCRIPT_TIP {
            get {
                return ResourceManager.GetString("DB_BROWSER_RUN_SCRIPT_TIP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Skip foreign key testing.
        /// </summary>
        internal static string DB_BROWSER_SKIP_FK_TEST {
            get {
                return ResourceManager.GetString("DB_BROWSER_SKIP_FK_TEST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Soft update (preserving data).
        /// </summary>
        internal static string DB_BROWSER_SOFT_UPDATE {
            get {
                return ResourceManager.GetString("DB_BROWSER_SOFT_UPDATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mismatches between database and mould detected:.
        /// </summary>
        internal static string DB_BROWSER_SUPPORT_PROBLEMS {
            get {
                return ResourceManager.GetString("DB_BROWSER_SUPPORT_PROBLEMS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Test.
        /// </summary>
        internal static string DB_BROWSER_TEST {
            get {
                return ResourceManager.GetString("DB_BROWSER_TEST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Test selected database.
        /// </summary>
        internal static string DB_BROWSER_TEST_TIP {
            get {
                return ResourceManager.GetString("DB_BROWSER_TEST_TIP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transformation of the mould.
        /// </summary>
        internal static string DB_BROWSER_TRANSFORMATION_MOULD {
            get {
                return ResourceManager.GetString("DB_BROWSER_TRANSFORMATION_MOULD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Updating database structure.
        /// </summary>
        internal static string DB_BROWSER_UPDATE_DB_STRUCTURE {
            get {
                return ResourceManager.GetString("DB_BROWSER_UPDATE_DB_STRUCTURE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use type FileStream.
        /// </summary>
        internal static string DB_BROWSER_USE_FILESTREAM {
            get {
                return ResourceManager.GetString("DB_BROWSER_USE_FILESTREAM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Getting data.
        /// </summary>
        internal static string DB_GRABBER_GETTING_DATA {
            get {
                return ResourceManager.GetString("DB_GRABBER_GETTING_DATA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Init connection.
        /// </summary>
        internal static string DB_GRABBER_INIT_CONNECTION {
            get {
                return ResourceManager.GetString("DB_GRABBER_INIT_CONNECTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Init lists.
        /// </summary>
        internal static string DB_GRABBER_INIT_LISTS {
            get {
                return ResourceManager.GetString("DB_GRABBER_INIT_LISTS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Database guid: {0}.
        /// </summary>
        internal static string DB_GUID {
            get {
                return ResourceManager.GetString("DB_GUID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Database info:.
        /// </summary>
        internal static string DB_INFO {
            get {
                return ResourceManager.GetString("DB_INFO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Database name: {0}.
        /// </summary>
        internal static string DB_NAME {
            get {
                return ResourceManager.GetString("DB_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Database version: {0}.
        /// </summary>
        internal static string DB_VERSION {
            get {
                return ResourceManager.GetString("DB_VERSION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Field quantity mismatch.
        /// </summary>
        internal static string DictionaryBinder_FieldCountMismatch {
            get {
                return ResourceManager.GetString("DictionaryBinder_FieldCountMismatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Done.
        /// </summary>
        internal static string DONE {
            get {
                return ResourceManager.GetString("DONE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Call stack.
        /// </summary>
        internal static string EXCEPTION_CALLSTACK {
            get {
                return ResourceManager.GetString("EXCEPTION_CALLSTACK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exception details.
        /// </summary>
        internal static string EXCEPTION_DETAILS {
            get {
                return ResourceManager.GetString("EXCEPTION_DETAILS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Message.
        /// </summary>
        internal static string EXCEPTION_MESSAGE {
            get {
                return ResourceManager.GetString("EXCEPTION_MESSAGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Source.
        /// </summary>
        internal static string EXCEPTION_SOURCE {
            get {
                return ResourceManager.GetString("EXCEPTION_SOURCE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failure.
        /// </summary>
        internal static string FAIL {
            get {
                return ResourceManager.GetString("FAIL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Function.
        /// </summary>
        internal static string FUNCTION {
            get {
                return ResourceManager.GetString("FUNCTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Write log strategy is not set.
        /// </summary>
        internal static string GlobalManager_NoStrategy {
            get {
                return ResourceManager.GetString("GlobalManager_NoStrategy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log.
        /// </summary>
        internal static string LOG {
            get {
                return ResourceManager.GetString("LOG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Debug.
        /// </summary>
        internal static string LOG_DEBUG_TITLE {
            get {
                return ResourceManager.GetString("LOG_DEBUG_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Errors.
        /// </summary>
        internal static string LOG_ERRORS_TITLE {
            get {
                return ResourceManager.GetString("LOG_ERRORS_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log file.
        /// </summary>
        internal static string LOG_FILE {
            get {
                return ResourceManager.GetString("LOG_FILE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exception.
        /// </summary>
        internal static string LOG_GRID_EXCEPTION_TITLE {
            get {
                return ResourceManager.GetString("LOG_GRID_EXCEPTION_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type.
        /// </summary>
        internal static string LOG_GRID_LEVEL_TITLE {
            get {
                return ResourceManager.GetString("LOG_GRID_LEVEL_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Source.
        /// </summary>
        internal static string LOG_GRID_LOGGER_TITLE {
            get {
                return ResourceManager.GetString("LOG_GRID_LOGGER_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Message.
        /// </summary>
        internal static string LOG_GRID_MESSAGE_TITLE {
            get {
                return ResourceManager.GetString("LOG_GRID_MESSAGE_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Timestamp.
        /// </summary>
        internal static string LOG_GRID_TIMESTAMP_TITLE {
            get {
                return ResourceManager.GetString("LOG_GRID_TIMESTAMP_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Messages.
        /// </summary>
        internal static string LOG_INFO_TITLE {
            get {
                return ResourceManager.GetString("LOG_INFO_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Debug.
        /// </summary>
        internal static string LOG_LEVEL_DEBUG {
            get {
                return ResourceManager.GetString("LOG_LEVEL_DEBUG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        internal static string LOG_LEVEL_ERROR {
            get {
                return ResourceManager.GetString("LOG_LEVEL_ERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fatal.
        /// </summary>
        internal static string LOG_LEVEL_FATAL {
            get {
                return ResourceManager.GetString("LOG_LEVEL_FATAL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Info.
        /// </summary>
        internal static string LOG_LEVEL_INFO {
            get {
                return ResourceManager.GetString("LOG_LEVEL_INFO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warning.
        /// </summary>
        internal static string LOG_LEVEL_WARN {
            get {
                return ResourceManager.GetString("LOG_LEVEL_WARN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show Log File.
        /// </summary>
        internal static string LOG_SHOW_FILE_TITLE {
            get {
                return ResourceManager.GetString("LOG_SHOW_FILE_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warnings.
        /// </summary>
        internal static string LOG_WARINING_TITLE {
            get {
                return ResourceManager.GetString("LOG_WARINING_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Database change conflict.
        /// </summary>
        internal static string MOULD_CHANGE_CONFLICT {
            get {
                return ResourceManager.GetString("MOULD_CHANGE_CONFLICT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to perform soft update: foreign key on {0} is mandatory.
        /// </summary>
        internal static string MOULD_COMPARE_MANDATORY_FK {
            get {
                return ResourceManager.GetString("MOULD_COMPARE_MANDATORY_FK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  {0} was not found in database.
        /// </summary>
        internal static string NOT_FOUND_IN_DATABASE {
            get {
                return ResourceManager.GetString("NOT_FOUND_IN_DATABASE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  {0} not found in mould.
        /// </summary>
        internal static string NOT_FOUND_IN_MD {
            get {
                return ResourceManager.GetString("NOT_FOUND_IN_MD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  {0} has object Guid &quot;{1}&quot; instead of &quot;{2}.
        /// </summary>
        internal static string NOT_WRONG_GUID {
            get {
                return ResourceManager.GetString("NOT_WRONG_GUID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  {0} has version &quot;{1}&quot; instead of &quot;{2}.
        /// </summary>
        internal static string NOT_WRONG_VERSION {
            get {
                return ResourceManager.GetString("NOT_WRONG_VERSION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        internal static string OK {
            get {
                return ResourceManager.GetString("OK", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap p_16_error {
            get {
                object obj = ResourceManager.GetObject("p_16_error", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap p_16_help {
            get {
                object obj = ResourceManager.GetObject("p_16_help", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap p_16_ok {
            get {
                object obj = ResourceManager.GetObject("p_16_ok", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap p_16_warning {
            get {
                object obj = ResourceManager.GetObject("p_16_warning", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap p_32_database_add {
            get {
                object obj = ResourceManager.GetObject("p_32_database_add", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap p_32_database_delete {
            get {
                object obj = ResourceManager.GetObject("p_32_database_delete", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap p_32_database_into {
            get {
                object obj = ResourceManager.GetObject("p_32_database_into", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap p_32_database_refresh {
            get {
                object obj = ResourceManager.GetObject("p_32_database_refresh", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap p_32_database_restore {
            get {
                object obj = ResourceManager.GetObject("p_32_database_restore", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap p_32_database_run {
            get {
                object obj = ResourceManager.GetObject("p_32_database_run", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap p_32_database_save {
            get {
                object obj = ResourceManager.GetObject("p_32_database_save", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap p_32_database_script {
            get {
                object obj = ResourceManager.GetObject("p_32_database_script", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap p_32_refresh {
            get {
                object obj = ResourceManager.GetObject("p_32_refresh", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap p_32_server_add {
            get {
                object obj = ResourceManager.GetObject("p_32_server_add", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap p_32_server_refresh {
            get {
                object obj = ResourceManager.GetObject("p_32_server_refresh", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap p_32_server_remove {
            get {
                object obj = ResourceManager.GetObject("p_32_server_remove", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap p_48_database_add {
            get {
                object obj = ResourceManager.GetObject("p_48_database_add", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap p_48_database_into {
            get {
                object obj = ResourceManager.GetObject("p_48_database_into", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap p_48_database_restore {
            get {
                object obj = ResourceManager.GetObject("p_48_database_restore", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap p_48_database_save {
            get {
                object obj = ResourceManager.GetObject("p_48_database_save", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap p_48_database_script {
            get {
                object obj = ResourceManager.GetObject("p_48_database_script", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap p_48_login {
            get {
                object obj = ResourceManager.GetObject("p_48_login", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap p_48_server_add {
            get {
                object obj = ResourceManager.GetObject("p_48_server_add", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap p_48_server_delete {
            get {
                object obj = ResourceManager.GetObject("p_48_server_delete", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap p_48_server_search {
            get {
                object obj = ResourceManager.GetObject("p_48_server_search", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap p_48_server_wait {
            get {
                object obj = ResourceManager.GetObject("p_48_server_wait", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Procedure.
        /// </summary>
        internal static string PROCEDURE {
            get {
                return ResourceManager.GetString("PROCEDURE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Field {0} is already used for sorting.
        /// </summary>
        internal static string QUERY_DUPLICATE_SORT_FIELD {
            get {
                return ResourceManager.GetString("QUERY_DUPLICATE_SORT_FIELD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid type. Must be a class implementing IBindable with public constructor without parameters.
        /// </summary>
        internal static string RecordManager_InvalidType {
            get {
                return ResourceManager.GetString("RecordManager_InvalidType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Record manager factory is not set. Use RecordManager.SetBinderFactory to fix it.
        /// </summary>
        internal static string RecordManager_NoFactory {
            get {
                return ResourceManager.GetString("RecordManager_NoFactory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid type for binding. Must be {0}, found {1}.
        /// </summary>
        internal static string ReflectionBuilder_TypeMismatch {
            get {
                return ResourceManager.GetString("ReflectionBuilder_TypeMismatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Restart is reqired.
        /// </summary>
        internal static string RESTART_REQUIRED {
            get {
                return ResourceManager.GetString("RESTART_REQUIRED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Application settings.
        /// </summary>
        internal static string SETTINGS {
            get {
                return ResourceManager.GetString("SETTINGS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Generic settings.
        /// </summary>
        internal static string SETTINGS_GENERIC {
            get {
                return ResourceManager.GetString("SETTINGS_GENERIC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log core settings.
        /// </summary>
        internal static string SETTINGS_LOG_CORE {
            get {
                return ResourceManager.GetString("SETTINGS_LOG_CORE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log display settings.
        /// </summary>
        internal static string SETTINGS_LOG_DISPLAY {
            get {
                return ResourceManager.GetString("SETTINGS_LOG_DISPLAY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Debug.
        /// </summary>
        internal static string SETTINGS_LOG_DISPLAY_DEBUG {
            get {
                return ResourceManager.GetString("SETTINGS_LOG_DISPLAY_DEBUG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show debug messages.
        /// </summary>
        internal static string SETTINGS_LOG_DISPLAY_DEBUG_COLOR {
            get {
                return ResourceManager.GetString("SETTINGS_LOG_DISPLAY_DEBUG_COLOR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        internal static string SETTINGS_LOG_DISPLAY_ERROR_COLOR {
            get {
                return ResourceManager.GetString("SETTINGS_LOG_DISPLAY_ERROR_COLOR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Info.
        /// </summary>
        internal static string SETTINGS_LOG_DISPLAY_INFO_COLOR {
            get {
                return ResourceManager.GetString("SETTINGS_LOG_DISPLAY_INFO_COLOR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warining.
        /// </summary>
        internal static string SETTINGS_LOG_DISPLAY_WARN_COLOR {
            get {
                return ResourceManager.GetString("SETTINGS_LOG_DISPLAY_WARN_COLOR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Restart.
        /// </summary>
        internal static string SETTINGS_RESTART_TITLE {
            get {
                return ResourceManager.GetString("SETTINGS_RESTART_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Restart is required. Do you wish to restart now ?.
        /// </summary>
        internal static string SETTINGS_RESTART_WARNING {
            get {
                return ResourceManager.GetString("SETTINGS_RESTART_WARNING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add SQL Server.
        /// </summary>
        internal static string SQL_ADD_SERVER {
            get {
                return ResourceManager.GetString("SQL_ADD_SERVER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check connection.
        /// </summary>
        internal static string SQL_CHECK_SERVER {
            get {
                return ResourceManager.GetString("SQL_CHECK_SERVER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error while cheching SQL Connection.
        /// </summary>
        internal static string SQL_CHECKING_CONNECTION_FAIL {
            get {
                return ResourceManager.GetString("SQL_CHECKING_CONNECTION_FAIL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Server connection failed. Check log for details.
        /// </summary>
        internal static string SQL_CHECKING_FAILURE {
            get {
                return ResourceManager.GetString("SQL_CHECKING_FAILURE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Checking connection.
        /// </summary>
        internal static string SQL_CHECKING_SERVER {
            get {
                return ResourceManager.GetString("SQL_CHECKING_SERVER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Server connection OK.
        /// </summary>
        internal static string SQL_CHECKING_SUCCESS {
            get {
                return ResourceManager.GetString("SQL_CHECKING_SUCCESS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Checking databases.
        /// </summary>
        internal static string SQL_CHECKING_VERSIONS {
            get {
                return ResourceManager.GetString("SQL_CHECKING_VERSIONS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to get database list from : {0}.
        /// </summary>
        internal static string SQL_GET_DATABASE_LIST_FAIL {
            get {
                return ResourceManager.GetString("SQL_GET_DATABASE_LIST_FAIL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Retrieving database list.
        /// </summary>
        internal static string SQL_GETTING_BASES {
            get {
                return ResourceManager.GetString("SQL_GETTING_BASES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Getting maximum version.
        /// </summary>
        internal static string SQL_GETTING_MAX_VERSION {
            get {
                return ResourceManager.GetString("SQL_GETTING_MAX_VERSION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Incorrect format of the version: it must consist of four point-separated integers.
        /// </summary>
        internal static string SQL_INCORRECT_VERSION {
            get {
                return ResourceManager.GetString("SQL_INCORRECT_VERSION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to read field, indexer is not initialized. Call OpenReader().
        /// </summary>
        internal static string Sql_IndexerUninitialized {
            get {
                return ResourceManager.GetString("Sql_IndexerUninitialized", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connection to database failed. Please check connection settings.
        /// </summary>
        internal static string Sql_InvalidConnection {
            get {
                return ResourceManager.GetString("Sql_InvalidConnection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value FilterOperation {0} is invalid.
        /// </summary>
        internal static string Sql_InvalidFilterOperation {
            get {
                return ResourceManager.GetString("Sql_InvalidFilterOperation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown error while executong query.
        /// </summary>
        internal static string Sql_InvalidQuery {
            get {
                return ResourceManager.GetString("Sql_InvalidQuery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Call InitList() before calling Next().
        /// </summary>
        internal static string Sql_NextWithoutInitList {
            get {
                return ResourceManager.GetString("Sql_NextWithoutInitList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alternative search ( Slower ).
        /// </summary>
        internal static string SQLEDIT_ALTSEARCH {
            get {
                return ResourceManager.GetString("SQLEDIT_ALTSEARCH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Authentification.
        /// </summary>
        internal static string SQLEDIT_AUTH_GROUP {
            get {
                return ResourceManager.GetString("SQLEDIT_AUTH_GROUP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type.
        /// </summary>
        internal static string SQLEDIT_AUTHTYPE {
            get {
                return ResourceManager.GetString("SQLEDIT_AUTHTYPE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SQL Server.
        /// </summary>
        internal static string SQLEDIT_AUTHTYPE_SQL {
            get {
                return ResourceManager.GetString("SQLEDIT_AUTHTYPE_SQL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Windows.
        /// </summary>
        internal static string SQLEDIT_AUTHTYPE_WIN {
            get {
                return ResourceManager.GetString("SQLEDIT_AUTHTYPE_WIN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Server.
        /// </summary>
        internal static string SQLEDIT_COMPUTER {
            get {
                return ResourceManager.GetString("SQLEDIT_COMPUTER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Instance name.
        /// </summary>
        internal static string SQLEDIT_INSTANCE {
            get {
                return ResourceManager.GetString("SQLEDIT_INSTANCE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Server location.
        /// </summary>
        internal static string SQLEDIT_LOCATION_GROUP {
            get {
                return ResourceManager.GetString("SQLEDIT_LOCATION_GROUP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login.
        /// </summary>
        internal static string SQLEDIT_LOGIN {
            get {
                return ResourceManager.GetString("SQLEDIT_LOGIN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        internal static string SQLEDIT_PASS {
            get {
                return ResourceManager.GetString("SQLEDIT_PASS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Database is fully consistent with the mould.
        /// </summary>
        internal static string STATUS_DESCRIPTION_FULL {
            get {
                return ResourceManager.GetString("STATUS_DESCRIPTION_FULL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mould contains some objects missed in the database or their versions are not consistent.
        /// </summary>
        internal static string STATUS_DESCRIPTION_NONE {
            get {
                return ResourceManager.GetString("STATUS_DESCRIPTION_NONE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Database contains objects not existing in the mould.
        /// </summary>
        internal static string STATUS_DESCRIPTION_PARTIAL {
            get {
                return ResourceManager.GetString("STATUS_DESCRIPTION_PARTIAL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error occured during checking database.
        /// </summary>
        internal static string STATUS_DESCRIPTION_UNKNOWN {
            get {
                return ResourceManager.GetString("STATUS_DESCRIPTION_UNKNOWN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Table.
        /// </summary>
        internal static string TABLE {
            get {
                return ResourceManager.GetString("TABLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View.
        /// </summary>
        internal static string VIEW {
            get {
                return ResourceManager.GetString("VIEW", resourceCulture);
            }
        }
    }
}
