//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.237
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RegisterDataImport.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("RegisterDataImport.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        internal static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Column index.
        /// </summary>
        internal static string ImportForm_ColumnIndex {
            get {
                return ResourceManager.GetString("ImportForm_ColumnIndex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Column name.
        /// </summary>
        internal static string ImportForm_ColumnName {
            get {
                return ResourceManager.GetString("ImportForm_ColumnName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Encoding.
        /// </summary>
        internal static string ImportForm_Encoding {
            get {
                return ResourceManager.GetString("ImportForm_Encoding", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File name.
        /// </summary>
        internal static string ImportForm_FileName {
            get {
                return ResourceManager.GetString("ImportForm_FileName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No columns selected.
        /// </summary>
        internal static string ImportForm_NoColumns {
            get {
                return ResourceManager.GetString("ImportForm_NoColumns", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Encoding is not selected.
        /// </summary>
        internal static string ImportForm_NoEncoding {
            get {
                return ResourceManager.GetString("ImportForm_NoEncoding", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File is not selected.
        /// </summary>
        internal static string ImportForm_NoFile {
            get {
                return ResourceManager.GetString("ImportForm_NoFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Separator is not selected.
        /// </summary>
        internal static string ImportForm_NoSeparator {
            get {
                return ResourceManager.GetString("ImportForm_NoSeparator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Table is not selected.
        /// </summary>
        internal static string ImportForm_NoTable {
            get {
                return ResourceManager.GetString("ImportForm_NoTable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Retrieve default.
        /// </summary>
        internal static string ImportForm_RetrieveDeafult {
            get {
                return ResourceManager.GetString("ImportForm_RetrieveDeafult", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Separator.
        /// </summary>
        internal static string ImportForm_Separator {
            get {
                return ResourceManager.GetString("ImportForm_Separator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Table.
        /// </summary>
        internal static string ImportForm_Table {
            get {
                return ResourceManager.GetString("ImportForm_Table", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CSV Import into table {0}.
        /// </summary>
        internal static string ImportForm_TableTitle {
            get {
                return ResourceManager.GetString("ImportForm_TableTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CSV Import.
        /// </summary>
        internal static string ImportForm_Title {
            get {
                return ResourceManager.GetString("ImportForm_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warning.
        /// </summary>
        internal static string Warning {
            get {
                return ResourceManager.GetString("Warning", resourceCulture);
            }
        }
    }
}
