//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.3603
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AT.Toolbox.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AT.Toolbox.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancelled.
        /// </summary>
        internal static string CANCELLED {
            get {
                return ResourceManager.GetString("CANCELLED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancelling.
        /// </summary>
        internal static string CANCELLING {
            get {
                return ResourceManager.GetString("CANCELLING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Completed.
        /// </summary>
        internal static string COMPLETED {
            get {
                return ResourceManager.GetString("COMPLETED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error while configuring application. Config file may be damaged. Setting default values.
        /// </summary>
        internal static string CONFIG_ERROR_FILE {
            get {
                return ResourceManager.GetString("CONFIG_ERROR_FILE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failure saving config..
        /// </summary>
        internal static string CONFIG_ERROR_SAVE {
            get {
                return ResourceManager.GetString("CONFIG_ERROR_SAVE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No valid config file.
        /// </summary>
        internal static string CONFIG_NO_FILE {
            get {
                return ResourceManager.GetString("CONFIG_NO_FILE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Only one application instance is allowed.
        /// </summary>
        internal static string CONFIG_NO_INSTANCE {
            get {
                return ResourceManager.GetString("CONFIG_NO_INSTANCE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No config file found, setting default values..
        /// </summary>
        internal static string CONFIG_WARNING_FILE {
            get {
                return ResourceManager.GetString("CONFIG_WARNING_FILE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        internal static string ERROR {
            get {
                return ResourceManager.GetString("ERROR", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap ICO_FULL_SUPPORT {
            get {
                object obj = ResourceManager.GetObject("ICO_FULL_SUPPORT", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ICO_NO_SUPPORT {
            get {
                object obj = ResourceManager.GetObject("ICO_NO_SUPPORT", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ICO_PARTIAL_SUPPORT {
            get {
                object obj = ResourceManager.GetObject("ICO_PARTIAL_SUPPORT", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ICO_UNKNOWN_SUPPORT {
            get {
                object obj = ResourceManager.GetObject("ICO_UNKNOWN_SUPPORT", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed acquiring MainModule.
        /// </summary>
        internal static string INIT_NO_MODULE {
            get {
                return ResourceManager.GetString("INIT_NO_MODULE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configuration section must be a non-abstract class with paramrterless constructor and inherited from AT.Toolbox.ConfigurationSection.
        /// </summary>
        internal static string INVALID_CONFIG_SECTION_TYPE {
            get {
                return ResourceManager.GetString("INVALID_CONFIG_SECTION_TYPE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delegate type {0} is not recognized as EventHandler&lt;{1}&gt;.
        /// </summary>
        internal static string INVALID_EVENT_HANDLER {
            get {
                return ResourceManager.GetString("INVALID_EVENT_HANDLER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} has invalid value of the property {1}.
        /// </summary>
        internal static string INVALID_LOOKUP_PROPERTY {
            get {
                return ResourceManager.GetString("INVALID_LOOKUP_PROPERTY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lookup for the type {0} is not parametrized.
        /// </summary>
        internal static string LOOKUP_NO_PARAMS {
            get {
                return ResourceManager.GetString("LOOKUP_NO_PARAMS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lookup type {0} must be set up before using.
        /// </summary>
        internal static string LOOKUP_NOT_SET {
            get {
                return ResourceManager.GetString("LOOKUP_NOT_SET", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pending.
        /// </summary>
        internal static string PENDING {
            get {
                return ResourceManager.GetString("PENDING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Running.
        /// </summary>
        internal static string RUNNING {
            get {
                return ResourceManager.GetString("RUNNING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string STR_COLOR_SCHEME_BLUE {
            get {
                return ResourceManager.GetString("STR_COLOR_SCHEME_BLUE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string STR_COLOR_SCHEME_BLUE_2 {
            get {
                return ResourceManager.GetString("STR_COLOR_SCHEME_BLUE_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string STR_COLOR_SCHEME_BLUE_INVERSE {
            get {
                return ResourceManager.GetString("STR_COLOR_SCHEME_BLUE_INVERSE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string STR_COLOR_SCHEME_BLUE_SELECTION {
            get {
                return ResourceManager.GetString("STR_COLOR_SCHEME_BLUE_SELECTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string STR_COLOR_SCHEME_BW {
            get {
                return ResourceManager.GetString("STR_COLOR_SCHEME_BW", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string STR_COLOR_SCHEME_BW_INV {
            get {
                return ResourceManager.GetString("STR_COLOR_SCHEME_BW_INV", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string STR_COLOR_SCHEME_COOL {
            get {
                return ResourceManager.GetString("STR_COLOR_SCHEME_COOL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string STR_COLOR_SCHEME_RED_YELLOW {
            get {
                return ResourceManager.GetString("STR_COLOR_SCHEME_RED_YELLOW", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string STR_COLOR_SCHEME_SEARCH {
            get {
                return ResourceManager.GetString("STR_COLOR_SCHEME_SEARCH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string STR_COLOR_SCHEME_SEARCH_2 {
            get {
                return ResourceManager.GetString("STR_COLOR_SCHEME_SEARCH_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string STR_COLOR_SCHEME_TOPO {
            get {
                return ResourceManager.GetString("STR_COLOR_SCHEME_TOPO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Internal work fault detected. See inner exception for details.
        /// </summary>
        internal static string WORK_FAULT {
            get {
                return ResourceManager.GetString("WORK_FAULT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wrong parameter type description.
        /// </summary>
        internal static string WRONG_PARAMETER_TYPE_DESCRIPTION {
            get {
                return ResourceManager.GetString("WRONG_PARAMETER_TYPE_DESCRIPTION", resourceCulture);
            }
        }
    }
}
