//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.225
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AT.Toolbox.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AT.Toolbox.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Abort.
        /// </summary>
        internal static string ABORT {
            get {
                return ResourceManager.GetString("ABORT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        internal static string ABOUT_TITLE {
            get {
                return ResourceManager.GetString("ABOUT_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Allow only one instance.
        /// </summary>
        internal static string ALLOW_ONE_INSTANCE {
            get {
                return ResourceManager.GetString("ALLOW_ONE_INSTANCE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can&apos;t open help file.
        /// </summary>
        internal static string APPHELP_CANT_OPEN_HELPFILE {
            get {
                return ResourceManager.GetString("APPHELP_CANT_OPEN_HELPFILE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Help file does not set.
        /// </summary>
        internal static string APPHELP_NOHELPFILE {
            get {
                return ResourceManager.GetString("APPHELP_NOHELPFILE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure want to exit the application?.
        /// </summary>
        internal static string APPLICATION_COMMIT_CLOSE {
            get {
                return ResourceManager.GetString("APPLICATION_COMMIT_CLOSE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Application Settings.
        /// </summary>
        internal static string APPLICATION_SETTINGS {
            get {
                return ResourceManager.GetString("APPLICATION_SETTINGS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Apply.
        /// </summary>
        internal static string APPLY {
            get {
                return ResourceManager.GetString("APPLY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Message buffer is overfulled. Please set up buffer size in log settings.
        /// </summary>
        internal static string BUFFER_OVER {
            get {
                return ResourceManager.GetString("BUFFER_OVER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        internal static string CANCEL {
            get {
                return ResourceManager.GetString("CANCEL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear.
        /// </summary>
        internal static string CLEAR {
            get {
                return ResourceManager.GetString("CLEAR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        internal static string CLOSE {
            get {
                return ResourceManager.GetString("CLOSE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Details.
        /// </summary>
        internal static string COL_DETAILS {
            get {
                return ResourceManager.GetString("COL_DETAILS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Event time.
        /// </summary>
        internal static string COL_EVENT_TIME {
            get {
                return ResourceManager.GetString("COL_EVENT_TIME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Message.
        /// </summary>
        internal static string COL_MESSAGE {
            get {
                return ResourceManager.GetString("COL_MESSAGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Source.
        /// </summary>
        internal static string COL_SOURCE {
            get {
                return ResourceManager.GetString("COL_SOURCE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Config file path.
        /// </summary>
        internal static string CONFIG_FILE_PATH {
            get {
                return ResourceManager.GetString("CONFIG_FILE_PATH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copyright.
        /// </summary>
        internal static string COPYRIGHT_TITLE {
            get {
                return ResourceManager.GetString("COPYRIGHT_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure to delete item?.
        /// </summary>
        internal static string DELETE_CONFIRM {
            get {
                return ResourceManager.GetString("DELETE_CONFIRM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Developed by.
        /// </summary>
        internal static string DEVELOPED_TITLE {
            get {
                return ResourceManager.GetString("DEVELOPED_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Don&apos;t close on critical error.
        /// </summary>
        internal static string DONT_CLOSE {
            get {
                return ResourceManager.GetString("DONT_CLOSE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Office 2003.
        /// </summary>
        internal static string DRAWING_OFFICE_2003 {
            get {
                return ResourceManager.GetString("DRAWING_OFFICE_2003", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Asphalt Skin.
        /// </summary>
        internal static string DRAWING_SKIN_ASPHALT {
            get {
                return ResourceManager.GetString("DRAWING_SKIN_ASPHALT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Blue Skin.
        /// </summary>
        internal static string DRAWING_SKIN_BLUE {
            get {
                return ResourceManager.GetString("DRAWING_SKIN_BLUE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Caramel Skin.
        /// </summary>
        internal static string DRAWING_SKIN_CARAMEL {
            get {
                return ResourceManager.GetString("DRAWING_SKIN_CARAMEL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Windows standard.
        /// </summary>
        internal static string DRAWING_WIN32 {
            get {
                return ResourceManager.GetString("DRAWING_WIN32", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure to save modified record?.
        /// </summary>
        internal static string EDIT_CONFIRM {
            get {
                return ResourceManager.GetString("EDIT_CONFIRM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        internal static string ERROR {
            get {
                return ResourceManager.GetString("ERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Call stack.
        /// </summary>
        internal static string EXCEPTION_CALLSTACK {
            get {
                return ResourceManager.GetString("EXCEPTION_CALLSTACK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Call stack.
        /// </summary>
        internal static string EXCEPTION_CALLSTACK1 {
            get {
                return ResourceManager.GetString("EXCEPTION_CALLSTACK1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exception details.
        /// </summary>
        internal static string EXCEPTION_DETAILS {
            get {
                return ResourceManager.GetString("EXCEPTION_DETAILS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Message.
        /// </summary>
        internal static string EXCEPTION_MESSAGE {
            get {
                return ResourceManager.GetString("EXCEPTION_MESSAGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Source.
        /// </summary>
        internal static string EXCEPTION_SOURCE {
            get {
                return ResourceManager.GetString("EXCEPTION_SOURCE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Source.
        /// </summary>
        internal static string EXCEPTION_SOURCE1 {
            get {
                return ResourceManager.GetString("EXCEPTION_SOURCE1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failure.
        /// </summary>
        internal static string FAIL {
            get {
                return ResourceManager.GetString("FAIL", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap foward_32 {
            get {
                object obj = ResourceManager.GetObject("foward_32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contents.
        /// </summary>
        internal static string HELP_BROWSER_CONTENTS {
            get {
                return ResourceManager.GetString("HELP_BROWSER_CONTENTS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Index.
        /// </summary>
        internal static string HELP_BROWSER_INDEX {
            get {
                return ResourceManager.GetString("HELP_BROWSER_INDEX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AudiTech help browser.
        /// </summary>
        internal static string HELP_BROWSER_TITLE {
            get {
                return ResourceManager.GetString("HELP_BROWSER_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Icon.
        /// </summary>
        internal static string ICON {
            get {
                return ResourceManager.GetString("ICON", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ignore.
        /// </summary>
        internal static string IGNORE {
            get {
                return ResourceManager.GetString("IGNORE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Additional Info.
        /// </summary>
        internal static string INFO_TITLE {
            get {
                return ResourceManager.GetString("INFO_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Message window.
        /// </summary>
        internal static string INFO_WND {
            get {
                return ResourceManager.GetString("INFO_WND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Initialization failure.
        /// </summary>
        internal static string INIT_FAIL {
            get {
                return ResourceManager.GetString("INIT_FAIL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to init Application instance.
        ///Would You like to check settings ?.
        /// </summary>
        internal static string INIT_FAIL_DESCRIPTION {
            get {
                return ResourceManager.GetString("INIT_FAIL_DESCRIPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Program performed an invalid operation and will be closed.
        /// </summary>
        internal static string INVALID_OPERATION {
            get {
                return ResourceManager.GetString("INVALID_OPERATION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure to kill the task {0}?.
        /// </summary>
        internal static string KILL_TASK_CONFIRM {
            get {
                return ResourceManager.GetString("KILL_TASK_CONFIRM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Level.
        /// </summary>
        internal static string LEVEL {
            get {
                return ResourceManager.GetString("LEVEL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to List to end.
        /// </summary>
        internal static string LIST_TO_END {
            get {
                return ResourceManager.GetString("LIST_TO_END", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Locale.
        /// </summary>
        internal static string LOCALE {
            get {
                return ResourceManager.GetString("LOCALE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to English.
        /// </summary>
        internal static string LOCALE_ENGLISH {
            get {
                return ResourceManager.GetString("LOCALE_ENGLISH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Russian.
        /// </summary>
        internal static string LOCALE_RUSSIAN {
            get {
                return ResourceManager.GetString("LOCALE_RUSSIAN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log.
        /// </summary>
        internal static string LOG {
            get {
                return ResourceManager.GetString("LOG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear.
        /// </summary>
        internal static string LOG_CLEAR {
            get {
                return ResourceManager.GetString("LOG_CLEAR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Debug.
        /// </summary>
        internal static string LOG_DEBUG_TITLE {
            get {
                return ResourceManager.GetString("LOG_DEBUG_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Errors.
        /// </summary>
        internal static string LOG_ERRORS_TITLE {
            get {
                return ResourceManager.GetString("LOG_ERRORS_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log file.
        /// </summary>
        internal static string LOG_FILE {
            get {
                return ResourceManager.GetString("LOG_FILE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exception.
        /// </summary>
        internal static string LOG_GRID_EXCEPTION_TITLE {
            get {
                return ResourceManager.GetString("LOG_GRID_EXCEPTION_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type.
        /// </summary>
        internal static string LOG_GRID_LEVEL_TITLE {
            get {
                return ResourceManager.GetString("LOG_GRID_LEVEL_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Source.
        /// </summary>
        internal static string LOG_GRID_LOGGER_TITLE {
            get {
                return ResourceManager.GetString("LOG_GRID_LOGGER_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Message.
        /// </summary>
        internal static string LOG_GRID_MESSAGE_TITLE {
            get {
                return ResourceManager.GetString("LOG_GRID_MESSAGE_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Timestamp.
        /// </summary>
        internal static string LOG_GRID_TIMESTAMP_TITLE {
            get {
                return ResourceManager.GetString("LOG_GRID_TIMESTAMP_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Messages.
        /// </summary>
        internal static string LOG_INFO_TITLE {
            get {
                return ResourceManager.GetString("LOG_INFO_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All.
        /// </summary>
        internal static string LOG_LEVEL_ALL {
            get {
                return ResourceManager.GetString("LOG_LEVEL_ALL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Debug.
        /// </summary>
        internal static string LOG_LEVEL_DEBUG {
            get {
                return ResourceManager.GetString("LOG_LEVEL_DEBUG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        internal static string LOG_LEVEL_ERROR {
            get {
                return ResourceManager.GetString("LOG_LEVEL_ERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fatal.
        /// </summary>
        internal static string LOG_LEVEL_FATAL {
            get {
                return ResourceManager.GetString("LOG_LEVEL_FATAL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Info.
        /// </summary>
        internal static string LOG_LEVEL_INFO {
            get {
                return ResourceManager.GetString("LOG_LEVEL_INFO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warning.
        /// </summary>
        internal static string LOG_LEVEL_WARN {
            get {
                return ResourceManager.GetString("LOG_LEVEL_WARN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Minimal level.
        /// </summary>
        internal static string LOG_MIN_LEVEL {
            get {
                return ResourceManager.GetString("LOG_MIN_LEVEL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show Log File.
        /// </summary>
        internal static string LOG_SHOW_FILE_TITLE {
            get {
                return ResourceManager.GetString("LOG_SHOW_FILE_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warnings.
        /// </summary>
        internal static string LOG_WARINING_TITLE {
            get {
                return ResourceManager.GetString("LOG_WARINING_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;log4net&gt;
        ///  &lt;appender name=&quot;MainAppender&quot; type=&quot;log4net.Appender.RollingFileAppender&quot;&gt;
        ///    &lt;file type=&quot;log4net.Util.PatternString&quot; value=&quot;%property{appDataDir}\Logs\%property{appName}.log&quot; /&gt;
        ///    &lt;lockingModel type=&quot;log4net.Appender.FileAppender+MinimalLock&quot; /&gt;
        ///    &lt;appendToFile value=&quot;true&quot; /&gt;
        ///    &lt;rollingStyle value=&quot;Size&quot; /&gt;
        ///    &lt;maxSizeRollBackups value=&quot;10&quot; /&gt;
        ///    &lt;maximumFileSize value=&quot;5MB&quot; /&gt;
        ///    &lt;staticLogFileName value=&quot;true&quot; /&gt;
        ///    &lt;layout type=&quot;log4net.Layout.PatternLayout&quot;&gt;
        ///      &lt;con [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Log4netConfig {
            get {
                return ResourceManager.GetString("Log4netConfig", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modules.
        /// </summary>
        internal static string MODULES_TITLE {
            get {
                return ResourceManager.GetString("MODULES_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Multi edit.
        /// </summary>
        internal static string MultiEdit {
            get {
                return ResourceManager.GetString("MultiEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        internal static string NAME {
            get {
                return ResourceManager.GetString("NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No.
        /// </summary>
        internal static string NO {
            get {
                return ResourceManager.GetString("NO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        internal static string OK {
            get {
                return ResourceManager.GetString("OK", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap p_16_book {
            get {
                object obj = ResourceManager.GetObject("p_16_book", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap p_16_debug {
            get {
                object obj = ResourceManager.GetObject("p_16_debug", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap p_16_down {
            get {
                object obj = ResourceManager.GetObject("p_16_down", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap p_16_error {
            get {
                object obj = ResourceManager.GetObject("p_16_error", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap p_16_help {
            get {
                object obj = ResourceManager.GetObject("p_16_help", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap p_16_info {
            get {
                object obj = ResourceManager.GetObject("p_16_info", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap p_16_log {
            get {
                object obj = ResourceManager.GetObject("p_16_log", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap p_16_ok {
            get {
                object obj = ResourceManager.GetObject("p_16_ok", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap p_16_purge {
            get {
                object obj = ResourceManager.GetObject("p_16_purge", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap p_16_warning {
            get {
                object obj = ResourceManager.GetObject("p_16_warning", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap p_24_purge {
            get {
                object obj = ResourceManager.GetObject("p_24_purge", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap p_32_app_config {
            get {
                object obj = ResourceManager.GetObject("p_32_app_config", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap p_32_bug_mail {
            get {
                object obj = ResourceManager.GetObject("p_32_bug_mail", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap p_32_bug_mail1 {
            get {
                object obj = ResourceManager.GetObject("p_32_bug_mail1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap p_32_config {
            get {
                object obj = ResourceManager.GetObject("p_32_config", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap p_32_document_config {
            get {
                object obj = ResourceManager.GetObject("p_32_document_config", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap p_32_folder_config {
            get {
                object obj = ResourceManager.GetObject("p_32_folder_config", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap p_32_log {
            get {
                object obj = ResourceManager.GetObject("p_32_log", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap p_32_log_config {
            get {
                object obj = ResourceManager.GetObject("p_32_log_config", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap p_32_purge {
            get {
                object obj = ResourceManager.GetObject("p_32_purge", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap p_48_bug_mail {
            get {
                object obj = ResourceManager.GetObject("p_48_bug_mail", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap p_48_database_add {
            get {
                object obj = ResourceManager.GetObject("p_48_database_add", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap p_48_debug {
            get {
                object obj = ResourceManager.GetObject("p_48_debug", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap p_48_error {
            get {
                object obj = ResourceManager.GetObject("p_48_error", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap p_48_forbidden {
            get {
                object obj = ResourceManager.GetObject("p_48_forbidden", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap p_48_info {
            get {
                object obj = ResourceManager.GetObject("p_48_info", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap p_48_ok {
            get {
                object obj = ResourceManager.GetObject("p_48_ok", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap p_48_purge {
            get {
                object obj = ResourceManager.GetObject("p_48_purge", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap p_48_question {
            get {
                object obj = ResourceManager.GetObject("p_48_question", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap p_48_stop {
            get {
                object obj = ResourceManager.GetObject("p_48_stop", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap p_48_user_error {
            get {
                object obj = ResourceManager.GetObject("p_48_user_error", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap p_48_view_log {
            get {
                object obj = ResourceManager.GetObject("p_48_view_log", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap p_48_warning {
            get {
                object obj = ResourceManager.GetObject("p_48_warning", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Restart on critical Error.
        /// </summary>
        internal static string RESTART_ON_CRITICAL {
            get {
                return ResourceManager.GetString("RESTART_ON_CRITICAL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Restart is reqired.
        /// </summary>
        internal static string RESTART_REQUIRED {
            get {
                return ResourceManager.GetString("RESTART_REQUIRED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Retry.
        /// </summary>
        internal static string RETRY {
            get {
                return ResourceManager.GetString("RETRY", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap rewind_32 {
            get {
                object obj = ResourceManager.GetObject("rewind_32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Application settings.
        /// </summary>
        internal static string SETTINGS {
            get {
                return ResourceManager.GetString("SETTINGS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Generic settings.
        /// </summary>
        internal static string SETTINGS_GENERIC {
            get {
                return ResourceManager.GetString("SETTINGS_GENERIC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log core settings.
        /// </summary>
        internal static string SETTINGS_LOG_CORE {
            get {
                return ResourceManager.GetString("SETTINGS_LOG_CORE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log display settings.
        /// </summary>
        internal static string SETTINGS_LOG_DISPLAY {
            get {
                return ResourceManager.GetString("SETTINGS_LOG_DISPLAY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Debug.
        /// </summary>
        internal static string SETTINGS_LOG_DISPLAY_DEBUG {
            get {
                return ResourceManager.GetString("SETTINGS_LOG_DISPLAY_DEBUG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show debug messages.
        /// </summary>
        internal static string SETTINGS_LOG_DISPLAY_DEBUG_COLOR {
            get {
                return ResourceManager.GetString("SETTINGS_LOG_DISPLAY_DEBUG_COLOR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        internal static string SETTINGS_LOG_DISPLAY_ERROR_COLOR {
            get {
                return ResourceManager.GetString("SETTINGS_LOG_DISPLAY_ERROR_COLOR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Info.
        /// </summary>
        internal static string SETTINGS_LOG_DISPLAY_INFO_COLOR {
            get {
                return ResourceManager.GetString("SETTINGS_LOG_DISPLAY_INFO_COLOR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warining.
        /// </summary>
        internal static string SETTINGS_LOG_DISPLAY_WARN_COLOR {
            get {
                return ResourceManager.GetString("SETTINGS_LOG_DISPLAY_WARN_COLOR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log settings.
        /// </summary>
        internal static string SETTINGS_LOG_INFO {
            get {
                return ResourceManager.GetString("SETTINGS_LOG_INFO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Level.
        /// </summary>
        internal static string SETTINGS_LOG_LEVEL {
            get {
                return ResourceManager.GetString("SETTINGS_LOG_LEVEL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log path.
        /// </summary>
        internal static string SETTINGS_LOG_PATH {
            get {
                return ResourceManager.GetString("SETTINGS_LOG_PATH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recent count.
        /// </summary>
        internal static string SETTINGS_LOG_RECENT_COUNT {
            get {
                return ResourceManager.GetString("SETTINGS_LOG_RECENT_COUNT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Restart.
        /// </summary>
        internal static string SETTINGS_RESTART_TITLE {
            get {
                return ResourceManager.GetString("SETTINGS_RESTART_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Some of the changes made require restart of the application. Do you want to restart now?.
        /// </summary>
        internal static string SETTINGS_RESTART_WARNING {
            get {
                return ResourceManager.GetString("SETTINGS_RESTART_WARNING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Validate.
        /// </summary>
        internal static string SETTINGS_VALIDATE {
            get {
                return ResourceManager.GetString("SETTINGS_VALIDATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status.
        /// </summary>
        internal static string STATUS {
            get {
                return ResourceManager.GetString("STATUS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Some critical errors leaded to stop. View detail descripton for all messages to explain.
        /// </summary>
        internal static string SUMMARY_ERROR {
            get {
                return ResourceManager.GetString("SUMMARY_ERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to These messages contain only information and does not require anithing to do.
        /// </summary>
        internal static string SUMMARY_INFO {
            get {
                return ResourceManager.GetString("SUMMARY_INFO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Read these warnings and fix the problems detected.
        /// </summary>
        internal static string SUMMARY_WARNING {
            get {
                return ResourceManager.GetString("SUMMARY_WARNING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Task.
        /// </summary>
        internal static string TASK {
            get {
                return ResourceManager.GetString("TASK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Version.
        /// </summary>
        internal static string VERSION_TITLE {
            get {
                return ResourceManager.GetString("VERSION_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes.
        /// </summary>
        internal static string YES {
            get {
                return ResourceManager.GetString("YES", resourceCulture);
            }
        }
    }
}
